"use client";
import {useEffect,useMemo,useState} from "react";
import {domains,questions,Question} from "./question-bank";

type Test={id:string;name:string;description:string;weight?:number;minutes:number;questions:Question[];color:string};
type Saved={test:string;score:number;total:number;date:string};

function prepared(list:Question[]){return list.map((q,i)=>{const shift=(i*3+1)%4;const options=q.options.map((_,j)=>q.options[(j+shift)%4]);return{...q,options,answer:(4-shift)%4}})}

export default function Home(){
 const tests:Test[]=useMemo(()=>[
  ...domains.map(d=>({id:d.name,name:d.name,description:`Focused practice for the ${d.weight}% exam domain.`,weight:d.weight,minutes:Math.max(15,questions.filter(q=>q.domain===d.name).length*2),questions:questions.filter(q=>q.domain===d.name),color:d.color})),
  {id:"full",name:"Full weighted mock exam",description:"60 questions · official domain weighting · exam-day pacing",minutes:105,questions,color:"#17332f"}
 ],[]);
 const [view,setView]=useState<"home"|"catalog"|"exam"|"results">("home"),[active,setActive]=useState<Test|null>(null),[items,setItems]=useState<Question[]>([]),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<number,number>>({}),[flags,setFlags]=useState<number[]>([]),[seconds,setSeconds]=useState(0),[history,setHistory]=useState<Saved[]>([]);
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("admin-ascent-results")||"[]"))}catch{}},[]);
 useEffect(()=>{if(view!=="exam")return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);setView("results");return 0}return s-1}),1000);return()=>clearInterval(t)},[view]);
 function begin(t:Test){setActive(t);setItems(prepared(t.questions));setIndex(0);setAnswers({});setFlags([]);setSeconds(t.minutes*60);setView("exam")}
 const score=items.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0),pct=items.length?Math.round(score/items.length*100):0;
 function submit(){if(!active)return;const entry={test:active.name,score,total:items.length,date:new Date().toLocaleDateString()};const next=[entry,...history].slice(0,12);setHistory(next);localStorage.setItem("admin-ascent-results",JSON.stringify(next));setView("results")}
 function fmt(n:number){return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
 return <main className="shell"><aside><div className="brand"><b>A</b> Admin Ascent</div><nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}>⌂ <span>Study plan</span></button><button className={view==="catalog"?"active":""} onClick={()=>setView("catalog")}>✦ <span>8 practice tests</span></button><button onClick={()=>setView("catalog")}>◫ <span>Exam domains</span></button></nav><div className="side-card"><small>CURRENT EXAM FORMAT</small><div><strong>60</strong><i>questions</i></div><progress value="65" max="100"/><p>105 minutes · 65% passing benchmark · seven weighted domains.</p></div><div className="profile"><b>PM</b><span><strong>Patricia</strong><small>Platform Admin II candidate</small></span></div></aside>
 <section className="content"><header><span className="mobile">Admin Ascent</span><span>{view==="exam"?`Time left ${fmt(seconds)}`:"🔥 Retake with a plan"}</span></header>
 {view==="home"&&<div className="page"><section className="hero"><div><small>YOUR RETAKE SYSTEM</small><h1>Eight tests.<br/><em>One clear finish line.</em></h1><p>Master each official Platform Administrator II domain, then prove your readiness with a 60-question weighted simulation.</p><div className="actions"><button className="primary" onClick={()=>setView("catalog")}>Choose a practice test →</button><span>Progress saves on this device</span></div></div><div className="orbit"><div><strong>8</strong><small>PRACTICE TESTS</small></div></div></section>
 <section className="recovery"><div><small>BUILT FOR A RETAKE</small><h2>Use evidence, not hope.</h2></div><ol><li><b>1</b><span><strong>Test by domain</strong><small>Isolate the exact concepts costing you points.</small></span></li><li><b>2</b><span><strong>Review every miss</strong><small>Learn the deciding constraint behind each answer.</small></span></li><li><b>3</b><span><strong>Gate your retake</strong><small>Reach 80% on topics and 65%+ on mixed mocks.</small></span></li></ol></section>
 <section className="section"><div className="section-head"><div><small>OFFICIAL WEIGHTING</small><h2>The seven exam domains</h2></div><span>Platform Administrator II outline</span></div><div className="domain-grid">{domains.map(d=><article key={d.name}><div className="ring" style={{"--score":`${d.weight*3.6}deg`,"--accent":d.color} as React.CSSProperties}><b>{d.weight}%</b></div><div><h3>{d.name}</h3><p>{questions.filter(q=>q.domain===d.name).length} original scenarios</p></div><button className="tiny" onClick={()=>begin(tests.find(t=>t.id===d.name)!)}>Start</button></article>)}</div></section>
 <section className="lower"><article className="focus"><small>FINAL READINESS CHECK</small><h2>Full weighted mock</h2><p>60 scenario questions in 105 minutes, distributed according to Salesforce’s published exam weights.</p><button onClick={()=>begin(tests[7])}>Start the full simulation →</button></article><article className="week"><div className="section-head"><div><small>RECENT WORK</small><h2>Your attempts</h2></div><strong>{history.length}</strong></div>{history.length?<div className="history-mini">{history.slice(0,3).map((h,i)=><p key={i}><span>{h.test}</span><b>{Math.round(h.score/h.total*100)}%</b></p>)}</div>:<p>Complete a test to start your history.</p>}</article></section></div>}
 {view==="catalog"&&<div className="page catalog"><div className="catalog-head"><small>8 PRACTICE TESTS</small><h1>Practice with precision.</h1><p>Take the seven domains separately. When each feels solid, use the full mock to test pacing and mixed-scenario judgment.</p></div><div className="test-grid">{tests.map((t,i)=><article key={t.id} className={t.id==="full"?"full-test":""}><span className="test-number">0{i+1}</span><i style={{background:t.color}}/><div><small>{t.weight?`${t.weight}% OF EXAM`:"WEIGHTED SIMULATION"}</small><h2>{t.name}</h2><p>{t.description}</p></div><div className="test-meta"><span>{t.questions.length} questions</span><span>{t.minutes} min</span></div><button className="primary" onClick={()=>begin(t)}>Start test →</button></article>)}</div></div>}
 {view==="exam"&&active&&<div className="exam-page"><div className="exam-main"><div className="quiz-head"><button onClick={()=>setView("catalog")}>← Exit test</button><span>{active.name}</span><strong>{fmt(seconds)}</strong></div><div className="bar"><i style={{width:`${Object.keys(answers).length/items.length*100}%`}}/></div><article className="question"><div className="question-label"><small>{items[index].domain}</small><button className={flags.includes(index)?"flagged":""} onClick={()=>setFlags(f=>f.includes(index)?f.filter(x=>x!==index):[...f,index])}>⚑ {flags.includes(index)?"Flagged":"Flag for review"}</button></div><h1>{items[index].prompt}</h1><div className="options">{items[index].options.map((o,i)=>{const answered=answers[index]!==undefined;const state=!answered?"":i===items[index].answer?"correct":i===answers[index]?"wrong":"muted";return <button className={state} disabled={answered} key={o} onClick={()=>setAnswers(a=>a[index]!==undefined?a:{...a,[index]:i})}><b>{String.fromCharCode(65+i)}</b><span>{o}</span>{answered&&i===items[index].answer?<strong>✓</strong>:null}</button>})}</div>{answers[index]!==undefined&&<div className={`instant-feedback ${answers[index]===items[index].answer?"is-right":"is-wrong"}`}><h3>{answers[index]===items[index].answer?"Correct — well done.":"Not quite — here’s the distinction."}</h3><p><strong>Right answer:</strong> {items[index].options[items[index].answer]}</p><p>{items[index].rationale}</p></div>}<div className="exam-actions"><button className="secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>← Previous</button>{index<items.length-1?<button className="primary" disabled={answers[index]===undefined} onClick={()=>setIndex(i=>i+1)}>Next question →</button>:<button className="primary" disabled={answers[index]===undefined} onClick={submit}>Submit test</button>}</div></article></div><aside className="navigator"><small>QUESTION MAP</small><div>{items.map((_,i)=><button key={i} onClick={()=>setIndex(i)} className={`${i===index?"current ":""}${answers[i]!==undefined?"answered ":""}${flags.includes(i)?"flag":""}`}>{i+1}</button>)}</div><p><i/> Answered <i/> Flagged</p><button className="submit" onClick={submit}>Finish and score</button></aside></div>}
 {view==="results"&&active&&<div className="page results-page"><article className="results"><b className="spark">{pct>=65?"✓":"✦"}</b><small>{pct>=65?"PASSING RANGE":"KEEP BUILDING"}</small><h1>{pct>=65?"You cleared the benchmark.":"This attempt gave you a map."}</h1><p>You answered <strong>{score} of {items.length}</strong> correctly for a score of <strong>{pct}%</strong>. The official passing benchmark is 65%.</p><div className="scorebox"><div><b>{pct}%</b><small>OVERALL</small></div><div><b>{flags.length}</b><small>FLAGGED</small></div><div><b>{Object.keys(answers).length}</b><small>ANSWERED</small></div></div><div className="review-list">{items.map((q,i)=><details key={i} className={answers[i]===q.answer?"right":"miss"}><summary><b>{answers[i]===q.answer?"✓":"×"}</b><span>{i+1}. {q.prompt}</span></summary><p><strong>Correct answer:</strong> {q.options[q.answer]}</p><p>{q.rationale}</p></details>)}</div><div className="actions"><button className="primary" onClick={()=>begin(active)}>Retake this test</button><button className="secondary" onClick={()=>setView("catalog")}>All practice tests</button></div></article></div>}
 </section></main>
}
