"use client";
import {useEffect,useMemo,useState} from "react";
import {domains,questions,Question} from "./question-bank";

type Test={id:string;name:string;description:string;weight?:number;minutes:number;questions:Question[];color:string};
type Saved={test:string;score:number;total:number;date:string};

function prepared(list:Question[]){return list.map((q,i)=>{const shift=(i*3+1)%4;const options=q.options.map((_,j)=>q.options[(j+shift)%4]);const answers=q.answers.map(a=>(a-shift+4)%4).sort();return{...q,options,answers,answer:answers[0]}})}
function weightedMock(seed:number){const counts=[12,11,6,7,8,4,12];return domains.flatMap((d,di)=>{const pool=questions.filter(q=>q.domain===d.name);return Array.from({length:counts[di]},(_,i)=>pool[(i*7+seed*13)%pool.length])})}

export default function Home(){
 const tests:Test[]=useMemo(()=>[
  ...domains.map(d=>({id:d.name,name:d.name,description:`Focused practice for the ${d.weight}% exam domain.`,weight:d.weight,minutes:Math.max(15,questions.filter(q=>q.domain===d.name).length*2),questions:questions.filter(q=>q.domain===d.name),color:d.color})),
  ...[1,2,3].map((seed,i)=>({id:`mock-${seed}`,name:`Full weighted mock ${String.fromCharCode(65+i)}`,description:"60 questions · official domain weighting · exam-day pacing",minutes:105,questions:weightedMock(seed),color:["#17332f","#315f74","#774c68"][i]}))
 ],[]);
 const [view,setView]=useState<"home"|"catalog"|"exam"|"results">("home"),[active,setActive]=useState<Test|null>(null),[items,setItems]=useState<Question[]>([]),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<number,number[]>>({}),[checked,setChecked]=useState<number[]>([]),[flags,setFlags]=useState<number[]>([]),[seconds,setSeconds]=useState(0),[history,setHistory]=useState<Saved[]>([]);
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("admin-ascent-results")||"[]"))}catch{}},[]);
 useEffect(()=>{if(view!=="exam")return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(t);setView("results");return 0}return s-1}),1000);return()=>clearInterval(t)},[view]);
 function begin(t:Test){setActive(t);setItems(prepared(t.questions));setIndex(0);setAnswers({});setChecked([]);setFlags([]);setSeconds(t.minutes*60);setView("exam")}
 function correctAt(i:number){const picked=[...(answers[i]||[])].sort();return picked.length===items[i]?.answers.length&&picked.every((v,j)=>v===items[i].answers[j])}
 function choose(option:number){if(checked.includes(index))return;const current=answers[index]||[];if(items[index].select===1){setAnswers(a=>({...a,[index]:[option]}));setChecked(c=>[...c,index]);return}const next=current.includes(option)?current.filter(x=>x!==option):current.length<items[index].select?[...current,option]:current;setAnswers(a=>({...a,[index]:next}))}
 function checkMulti(){if((answers[index]||[]).length===items[index].select)setChecked(c=>c.includes(index)?c:[...c,index])}
 const score=items.reduce((n,_q,i)=>n+(correctAt(i)?1:0),0),pct=items.length?Math.round(score/items.length*100):0;
 function submit(){if(!active)return;const entry={test:active.name,score,total:items.length,date:new Date().toLocaleDateString()};const next=[entry,...history].slice(0,12);setHistory(next);localStorage.setItem("admin-ascent-results",JSON.stringify(next));setView("results")}
 function fmt(n:number){return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
 return <main className="shell"><aside><div className="brand"><b>A</b> Admin Ascent</div><nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}>⌂ <span>Study plan</span></button><button className={view==="catalog"?"active":""} onClick={()=>setView("catalog")}>✦ <span>10 practice tests</span></button><button onClick={()=>setView("catalog")}>◫ <span>Exam domains</span></button></nav><div className="side-card"><small>CURRENT EXAM FORMAT</small><div><strong>60</strong><i>questions</i></div><progress value="65" max="100"/><p>105 minutes · 65% passing benchmark · seven weighted domains.</p></div><div className="profile"><b>PM</b><span><strong>Patricia</strong><small>Platform Admin II candidate</small></span></div></aside>
 <section className="content"><header><span className="mobile">Admin Ascent</span><span>{view==="exam"?`Time left ${fmt(seconds)}`:"🔥 Retake with a plan"}</span></header>
 {view==="home"&&<div className="page"><section className="hero"><div><small>YOUR RETAKE SYSTEM</small><h1>Ten tests.<br/><em>One clear finish line.</em></h1><p>Practice from a 200+ question bank, master each official Platform Administrator II domain, then prove your readiness with three distinct weighted mocks.</p><div className="actions"><button className="primary" onClick={()=>setView("catalog")}>Choose a practice test →</button><span>Progress saves on this device</span></div></div><div className="orbit"><div><strong>10</strong><small>PRACTICE TESTS</small></div></div></section>
 <section className="recovery"><div><small>BUILT FOR A RETAKE</small><h2>Use evidence, not hope.</h2></div><ol><li><b>1</b><span><strong>Test by domain</strong><small>Isolate the exact concepts costing you points.</small></span></li><li><b>2</b><span><strong>Review every miss</strong><small>Learn the deciding constraint behind each answer.</small></span></li><li><b>3</b><span><strong>Gate your retake</strong><small>Reach 80% on topics and 65%+ on mixed mocks.</small></span></li></ol></section>
 <section className="section"><div className="section-head"><div><small>OFFICIAL WEIGHTING</small><h2>The seven exam domains</h2></div><span>Platform Administrator II outline</span></div><div className="domain-grid">{domains.map(d=><article key={d.name}><div className="ring" style={{"--score":`${d.weight*3.6}deg`,"--accent":d.color} as React.CSSProperties}><b>{d.weight}%</b></div><div><h3>{d.name}</h3><p>{questions.filter(q=>q.domain===d.name).length} original scenarios</p></div><button className="tiny" onClick={()=>begin(tests.find(t=>t.id===d.name)!)}>Start</button></article>)}</div></section>
 <section className="lower"><article className="focus"><small>FINAL READINESS CHECK</small><h2>Three weighted mocks</h2><p>Each mock contains 60 questions in 105 minutes, including multi-select items and Salesforce’s published domain weighting.</p><button onClick={()=>begin(tests[7])}>Start mock A →</button></article><article className="week"><div className="section-head"><div><small>RECENT WORK</small><h2>Your attempts</h2></div><strong>{history.length}</strong></div>{history.length?<div className="history-mini">{history.slice(0,3).map((h,i)=><p key={i}><span>{h.test}</span><b>{Math.round(h.score/h.total*100)}%</b></p>)}</div>:<p>Complete a test to start your history.</p>}</article></section></div>}
 {view==="catalog"&&<div className="page catalog"><div className="catalog-head"><small>10 PRACTICE TESTS</small><h1>Practice with precision.</h1><p>Take seven domain tests from the expanded bank, then use three distinct full mocks to test pacing, multi-select judgment, and retention.</p></div><div className="test-grid">{tests.map((t,i)=><article key={t.id} className={t.id.startsWith("mock")?"full-test":""}><span className="test-number">{String(i+1).padStart(2,"0")}</span><i style={{background:t.color}}/><div><small>{t.weight?`${t.weight}% OF EXAM`:"WEIGHTED SIMULATION"}</small><h2>{t.name}</h2><p>{t.description}</p></div><div className="test-meta"><span>{t.questions.length} questions</span><span>{t.minutes} min</span></div><button className="primary" onClick={()=>begin(t)}>Start test →</button></article>)}</div></div>}
 {view==="exam"&&active&&<div className="exam-page"><div className="exam-main"><div className="quiz-head"><button onClick={()=>setView("catalog")}>← Exit test</button><span>{active.name}</span><strong>{fmt(seconds)}</strong></div><div className="bar"><i style={{width:`${checked.length/items.length*100}%`}}/></div><article className="question"><div className="question-label"><small>{items[index].domain} · {items[index].select>1?`SELECT ${items[index].select}`:"SELECT ONE"}</small><button className={flags.includes(index)?"flagged":""} onClick={()=>setFlags(f=>f.includes(index)?f.filter(x=>x!==index):[...f,index])}>⚑ {flags.includes(index)?"Flagged":"Flag for review"}</button></div><h1>{items[index].prompt}</h1><div className="options">{items[index].options.map((o,i)=>{const graded=checked.includes(index),picked=(answers[index]||[]).includes(i);const state=!graded?(picked?"chosen":""):items[index].answers.includes(i)?"correct":picked?"wrong":"muted";return <button className={state} disabled={graded} key={o} onClick={()=>choose(i)}><b>{items[index].select>1?(picked?"✓":"□"):String.fromCharCode(65+i)}</b><span>{o}</span>{graded&&items[index].answers.includes(i)?<strong>✓</strong>:null}</button>})}</div>{items[index].select>1&&!checked.includes(index)&&<button className="check-answer" disabled={(answers[index]||[]).length!==items[index].select} onClick={checkMulti}>Check {items[index].select} answers</button>}{checked.includes(index)&&<div className={`instant-feedback ${correctAt(index)?"is-right":"is-wrong"}`}><h3>{correctAt(index)?"Correct — well done.":"Not quite — here’s the distinction."}</h3><p><strong>Right answer{items[index].answers.length>1?"s":""}:</strong> {items[index].answers.map(a=>items[index].options[a]).join(" + ")}</p><p>{items[index].rationale}</p></div>}<div className="exam-actions"><button className="secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>← Previous</button>{index<items.length-1?<button className="primary" disabled={!checked.includes(index)} onClick={()=>setIndex(i=>i+1)}>Next question →</button>:<button className="primary" disabled={!checked.includes(index)} onClick={submit}>Submit test</button>}</div></article></div><aside className="navigator"><small>QUESTION MAP</small><div>{items.map((_,i)=><button key={i} onClick={()=>setIndex(i)} className={`${i===index?"current ":""}${checked.includes(i)?"answered ":""}${flags.includes(i)?"flag":""}`}>{i+1}</button>)}</div><p><i/> Answered <i/> Flagged</p><button className="submit" onClick={submit}>Finish and score</button></aside></div>}
 {view==="results"&&active&&<div className="page results-page"><article className="results"><b className="spark">{pct>=65?"✓":"✦"}</b><small>{pct>=65?"PASSING RANGE":"KEEP BUILDING"}</small><h1>{pct>=65?"You cleared the benchmark.":"This attempt gave you a map."}</h1><p>You answered <strong>{score} of {items.length}</strong> correctly for a score of <strong>{pct}%</strong>. The official passing benchmark is 65%.</p><div className="scorebox"><div><b>{pct}%</b><small>OVERALL</small></div><div><b>{flags.length}</b><small>FLAGGED</small></div><div><b>{checked.length}</b><small>ANSWERED</small></div></div><div className="review-list">{items.map((q,i)=><details key={i} className={correctAt(i)?"right":"miss"}><summary><b>{correctAt(i)?"✓":"×"}</b><span>{i+1}. {q.prompt}</span></summary><p><strong>Correct answer{q.answers.length>1?"s":""}:</strong> {q.answers.map(a=>q.options[a]).join(" + ")}</p><p>{q.rationale}</p></details>)}</div><div className="actions"><button className="primary" onClick={()=>begin(active)}>Retake this test</button><button className="secondary" onClick={()=>setView("catalog")}>All practice tests</button></div></article></div>}
 </section></main>
}
