export type Question={domain:string;prompt:string;options:string[];answer:number;rationale:string};
const raw=`
Security and Access|A manager needs temporary access to one peer-owned Account. Best option?|Manual share|Move roles|View All Data|Public group|Manual sharing grants narrow record access without restructuring security.
Security and Access|Users can edit Accounts but not a sensitive field. Which control?|Field-level security|OWD|Sharing rule|Login hours|Field-level security controls visibility and editability at field level.
Security and Access|Which feature grants extra permissions only during an activated session?|Session-based permission set|Role hierarchy|Delegated admin|Restriction rule|Session-based permission sets activate access for a bounded session.
Security and Access|OWD is Private and peers need access to records meeting criteria. Use?|Criteria-based sharing rule|Profile|Manual sharing for every record|View All|A criteria-based rule automatically shares matching records.
Security and Access|What can reduce records visible after sharing has already granted access?|Restriction rule|Role hierarchy|Public group|Account team|Restriction rules filter the records a user can see after baseline access.
Security and Access|A delegated admin must manage users in specified roles only. Configure?|Delegated administration group|Permission set group|Queue|Territory|Delegated administration scopes which users and objects can be managed.
Security and Access|What provides temporary elevated access requiring a high-assurance session?|Session security level and session-based permission set|Role hierarchy|Login IP range only|Manual share|High-assurance sessions can gate temporary permission activation.
Security and Access|Which setting prevents login outside the corporate network for profile users?|Login IP ranges|Trusted IP ranges|OWD|Sharing rules|Profile login IP ranges block access from addresses outside the range.
Security and Access|A user has object Read but a field is hidden. Why?|Field-level security denies it|OWD is Private|Role is too low|Record type omits it|Field-level security overrides page layout visibility.
Security and Access|What is the safest way to aggregate several job permissions?|Permission set group|Clone System Administrator|Many profiles|View All Data|Permission set groups bundle least-privilege access by job function.
Security and Access|Which mechanism opens access upward by management structure?|Role hierarchy|Profile hierarchy|Queue hierarchy|Permission set group|The role hierarchy can grant managers access to subordinates' records.
Security and Access|To investigate unexpected record access, what should an admin inspect first?|User Record Access and sharing reasons|Page layout|Compact layout|App menu|Record-access details reveal why a user can access a record.
Objects and Applications|A child must be deleted with its parent and inherit ownership. Relationship?|Master-detail|Lookup|External lookup|Indirect lookup|Master-detail provides cascade delete and inherited ownership.
Objects and Applications|A parent needs a SUM of child values without code. Requirement?|Master-detail plus roll-up summary|Lookup plus formula|External ID|Junction list|Native roll-up summaries require master-detail.
Objects and Applications|How is a many-to-many model built?|Junction object with two master-detail relationships|Two formula fields|One hierarchical lookup|External object|A junction object joins two parents through master-detail relationships.
Objects and Applications|Different business processes need different picklist values. Use?|Record types|Compact layouts|Permission sets only|Queues|Record types control business process, picklist values, and page assignment.
Objects and Applications|Which page technology controls component visibility by criteria?|Lightning App Builder|Schema Builder|Object Manager only|Approval Builder|Lightning App Builder supports conditional component visibility.
Objects and Applications|A picklist value must be shared across objects. Use?|Global value set|Dependent lookup|Custom metadata only|Bucket field|A global value set provides reusable governed picklist values.
Objects and Applications|Which relationship links a Salesforce object to an external object by external ID?|Indirect lookup|Master-detail|Hierarchy|Self lookup|Indirect lookup matches an external object's field to a parent external ID.
Objects and Applications|What controls available stages for an Opportunity record type?|Sales process|Support process|Lead process|Path only|A sales process selects the Opportunity stages available to a record type.
Objects and Applications|Users need different home experiences by app and profile. Configure?|Lightning page activation|Page layout assignment|Compact layout|Search layout|Activation assigns Lightning pages by app, profile, and form factor.
Objects and Applications|What prevents deleting a lookup parent when children exist?|Lookup relationship with restricted delete|Master-detail reparenting|Roll-up summary|Formula field|Restricted delete blocks parent deletion when related children exist.
Objects and Applications|Which feature displays key fields in a mobile record header?|Compact layout|Search layout|Mini page layout|Record type|Compact layouts drive highlighted fields in several interfaces.
Auditing and Monitoring|Need field-value history beyond standard retention and scale. Use?|Field Audit Trail|Setup Audit Trail|Login History|Debug Logs|Field Audit Trail supports extended retention policies for tracked changes.
Auditing and Monitoring|Which log records configuration changes made in Setup?|Setup Audit Trail|Field History|Event Monitoring|Data Export|Setup Audit Trail records recent administrative configuration changes.
Auditing and Monitoring|Need details about user logins, URI events, and report exports. Use?|Event Monitoring|Debug logs only|Recycle Bin|Optimizer|Event Monitoring exposes event log files for user activity analysis.
Auditing and Monitoring|Where can an admin review successful and failed login attempts?|Login History|Setup Audit Trail|Field History|Apex Jobs|Login History records authentication attempts and related details.
Auditing and Monitoring|Which tool recommends improvements based on org configuration?|Salesforce Optimizer|Schema Builder|Data Loader|Health Check only|Optimizer analyzes features and configuration and suggests improvements.
Auditing and Monitoring|What compares security settings against a baseline standard?|Health Check|Event Monitoring|Field History|Debug Log|Health Check scores settings against Salesforce or custom baselines.
Cloud Applications|Opportunity splits must total what percentage for revenue splits?|100%|Any amount|50%|They cannot be edited|Revenue splits must total 100 percent.
Cloud Applications|Which feature assigns Accounts and Opportunities by geography or rules?|Enterprise Territory Management|Role hierarchy|Account teams only|Lead assignment|Territory Management models flexible market-based access and assignment.
Cloud Applications|Support needs milestone timers and service terms. Configure?|Entitlements and milestones|Escalation rules only|Queues only|Knowledge categories|Entitlements and milestones track support eligibility and time commitments.
Cloud Applications|Knowledge visibility must vary by audience and subject. Use?|Data categories and channel visibility|Record types only|Queues|Forecast categories|Categories classify articles while channels govern audience visibility.
Cloud Applications|Which feature guides sellers through stage-specific fields and coaching?|Path|Forecasting|Kanban only|Territories|Path presents key fields and guidance for each process stage.
Cloud Applications|Cases must route based on criteria when created. Use?|Case assignment rules|Escalation rules|Auto-response only|Approval process|Assignment rules route new cases to users or queues.
Cloud Applications|A service deadline is missed and management must be notified. Use?|Milestone action|Lead assignment|Opportunity split|Forecast adjustment|Milestone actions respond to warning or violation timing.
Data and Analytics|Identify existing duplicate Accounts at scale. Use?|Duplicate Jobs with matching rules|Mass Transfer|Schema Builder|Weekly export|Duplicate Jobs scan existing records using matching rules.
Data and Analytics|Executives need dashboards filtered for the logged-in viewer. Use?|Dynamic dashboard|Reporting snapshot|Joined report|Bucket field|Dynamic dashboards run as the viewing user.
Data and Analytics|Store report totals monthly for historical comparison. Use?|Reporting snapshot|Dashboard filter|Cross filter|Row-level formula|Reporting snapshots save summarized report results on a schedule.
Data and Analytics|Show Accounts without Opportunities in a report. Use?|Cross filter|Bucket field|Summary formula|Dashboard filter|Cross filters include or exclude records based on related objects.
Data and Analytics|Combine blocks from different report types in one report. Use?|Joined report|Matrix report|Tabular report|Reporting snapshot|Joined reports display multiple report blocks with shared groupings.
Data and Analytics|Categorize numeric ranges without creating a field. Use?|Bucket field|Summary formula|Custom metadata|Cross filter|Bucket fields categorize report values without changing the object.
Data and Analytics|Which feature validates import records against duplicate policy?|Duplicate rules|Sharing rules|Restriction rules|Escalation rules|Duplicate rules determine whether matching records are allowed or blocked.
Data and Analytics|Mass update millions of records with API support. Best tool?|Data Loader|Import Wizard|List view inline edit|Schema Builder|Data Loader supports large volumes and automated command-line operations.
Environment and Deployment|A validation rule references a new field. What must the change set include?|Both components and dependencies|Rule only|Field only|Object data|Dependent metadata must be deployed together.
Environment and Deployment|Which sandbox includes a full copy of production data?|Full sandbox|Developer sandbox|Developer Pro|Scratch org|A Full sandbox replicates production metadata and data.
Environment and Deployment|What should be run before a production change-set deployment?|Validate inbound change set|Refresh production|Delete tests|Data export only|Validation checks dependencies and tests without committing changes.
Environment and Deployment|Which sandbox is best for development with limited data storage?|Developer sandbox|Full sandbox|Partial Copy only|Production clone|Developer sandboxes are intended for coding and configuration work.
Process Automation|Need guided user input and branching from a record page. Use?|Screen Flow|Before-save flow|Scheduled flow|Approval only|Screen Flows provide interactive screens and branching.
Process Automation|Fast update to fields on the triggering record. Use?|Before-save record-triggered flow|After-save flow|Screen flow|Approval process|Before-save flows avoid an extra database update.
Process Automation|Update related records after a record commits. Use?|After-save record-triggered flow|Before-save flow|Autolaunched flow only|Formula field|After-save flows can create and update related records.
Process Automation|Prevent repeat execution when a field has not meaningfully changed. Use?|Entry conditions with prior-value checks|Scheduled path|Screen component|Queue|Prior-value checks restrict automation to meaningful transitions.
Process Automation|Route a record through formal multi-step sign-off. Use?|Approval process|Before-save flow|Formula field|Assignment rule|Approval processes provide submission, approvers, lock, and actions.
Process Automation|Run automation every night independent of a record change. Use?|Schedule-triggered flow|Before-save flow|Screen flow|Approval process|Schedule-triggered flows run at a defined time and frequency.
Process Automation|Wait five days after a date before sending a reminder. Use?|Scheduled path|Before-save update|Immediate action only|Validation rule|Scheduled paths defer flow actions relative to a time source.
Process Automation|Reusable no-screen logic invoked by another flow. Use?|Autolaunched flow|Screen flow|Approval process|Workflow email alert|Autolaunched flows encapsulate reusable logic without UI.
Process Automation|Which tool evaluates a value dynamically without storing it?|Formula field|Roll-up summary only|Scheduled flow|Approval process|Formula fields calculate values when records are queried.
Process Automation|A flow faults while creating a record. Best design?|Connect fault path and log actionable details|Ignore the fault|Add a loop|Use a page layout|Fault paths provide controlled error handling and diagnostics.
Process Automation|Apply different automation only when Status changes to Closed. Use?|Is Changed plus prior/current criteria|Run every update|Scheduled flow|Manual share|Change detection ensures transition-specific execution.
Process Automation|Complex logic exceeds declarative limits and needs transaction control. Consider?|Invocable Apex with Flow|More page layouts|A dashboard|A sharing rule|Invocable Apex can extend Flow for code-appropriate requirements.
`.trim();

export const questions:Question[]=raw.split("\n").map(line=>{const [domain,prompt,correct,...rest]=line.split("|");const rationale=rest.pop()!;const options=[correct,...rest];return{domain,prompt,options,answer:0,rationale}});
export const domains=[
 {name:"Security and Access",weight:20,color:"#f4a55e"},{name:"Objects and Applications",weight:19,color:"#72b9df"},{name:"Auditing and Monitoring",weight:10,color:"#9d8ce0"},{name:"Cloud Applications",weight:11,color:"#e7859f"},{name:"Data and Analytics",weight:13,color:"#63be9b"},{name:"Environment and Deployment",weight:7,color:"#d9a35f"},{name:"Process Automation",weight:20,color:"#ed725f"}
];
