export type Question={domain:string;prompt:string;options:string[];answer:number;answers:number[];select:number;rationale:string};
const raw=`
Security and Access|A manager needs temporary access to one peer-owned Account. Best option?|Manual share|Move roles|View All Data|Public group|Manual sharing grants narrow record access without restructuring security.
Security and Access|Users can edit Accounts but not a sensitive field. Which control?|Field-level security|OWD|Sharing rule|Login hours|Field-level security controls visibility and editability at field level.
Security and Access|Which feature grants extra permissions only during an activated session?|Session-based permission set|Role hierarchy|Delegated admin|Restriction rule|Session-based permission sets activate access for a bounded session.
Security and Access|OWD is Private and peers need access to records meeting criteria. Use?|Criteria-based sharing rule|Profile|Manual sharing for every record|View All|A criteria-based rule automatically shares matching records.
Security and Access|What can reduce records visible after sharing has already granted access?|Restriction rule|Role hierarchy|Public group|Account team|Restriction rules filter the records a user can see after baseline access.
Security and Access|A delegated admin must manage users in specified roles only. Configure?|Delegated administration group|Permission set group|Queue|Territory|Delegated administration scopes which users and objects can be managed.
Security and Access|What provides temporary elevated access requiring a high-assurance session?|Session security level and session-based permission set|Role hierarchy|Login IP range only|Manual share|High-assurance sessions can gate temporary permission activation.
Security and Access|Which setting prevents login outside the corporate network for profile users?|Login IP ranges|Trusted IP ranges|OWD|Sharing rules|Profile login IP ranges block access from addresses outside the range.
Security and Access|A user has object Read but a field is hidden. Why?|Field-level security denies it|OWD is Private|Role is too low|Record type omits it|Field-level security overrides page layout visibility.
Security and Access|What is the safest way to aggregate several job permissions?|Permission set group|Clone System Administrator|Many profiles|View All Data|Permission set groups bundle least-privilege access by job function.
Security and Access|Which mechanism opens access upward by management structure?|Role hierarchy|Profile hierarchy|Queue hierarchy|Permission set group|The role hierarchy can grant managers access to subordinates' records.
Security and Access|To investigate unexpected record access, what should an admin inspect first?|User Record Access and sharing reasons|Page layout|Compact layout|App menu|Record-access details reveal why a user can access a record.
Objects and Applications|A child must be deleted with its parent and inherit ownership. Relationship?|Master-detail|Lookup|External lookup|Indirect lookup|Master-detail provides cascade delete and inherited ownership.
Objects and Applications|A parent needs a SUM of child values without code. Requirement?|Master-detail plus roll-up summary|Lookup plus formula|External ID|Junction list|Native roll-up summaries require master-detail.
Objects and Applications|How is a many-to-many model built?|Junction object with two master-detail relationships|Two formula fields|One hierarchical lookup|External object|A junction object joins two parents through master-detail relationships.
Objects and Applications|Different business processes need different picklist values. Use?|Record types|Compact layouts|Permission sets only|Queues|Record types control business process, picklist values, and page assignment.
Objects and Applications|Which page technology controls component visibility by criteria?|Lightning App Builder|Schema Builder|Object Manager only|Approval Builder|Lightning App Builder supports conditional component visibility.
Objects and Applications|A picklist value must be shared across objects. Use?|Global value set|Dependent lookup|Custom metadata only|Bucket field|A global value set provides reusable governed picklist values.
Objects and Applications|Which relationship links a Salesforce object to an external object by external ID?|Indirect lookup|Master-detail|Hierarchy|Self lookup|Indirect lookup matches an external object's field to a parent external ID.
Objects and Applications|What controls available stages for an Opportunity record type?|Sales process|Support process|Lead process|Path only|A sales process selects the Opportunity stages available to a record type.
Objects and Applications|Users need different home experiences by app and profile. Configure?|Lightning page activation|Page layout assignment|Compact layout|Search layout|Activation assigns Lightning pages by app, profile, and form factor.
Objects and Applications|What prevents deleting a lookup parent when children exist?|Lookup relationship with restricted delete|Master-detail reparenting|Roll-up summary|Formula field|Restricted delete blocks parent deletion when related children exist.
Objects and Applications|Which feature displays key fields in a mobile record header?|Compact layout|Search layout|Mini page layout|Record type|Compact layouts drive highlighted fields in several interfaces.
Auditing and Monitoring|Need field-value history beyond standard retention and scale. Use?|Field Audit Trail|Setup Audit Trail|Login History|Debug Logs|Field Audit Trail supports extended retention policies for tracked changes.
Auditing and Monitoring|Which log records configuration changes made in Setup?|Setup Audit Trail|Field History|Event Monitoring|Data Export|Setup Audit Trail records recent administrative configuration changes.
Auditing and Monitoring|Need details about user logins, URI events, and report exports. Use?|Event Monitoring|Debug logs only|Recycle Bin|Optimizer|Event Monitoring exposes event log files for user activity analysis.
Auditing and Monitoring|Where can an admin review successful and failed login attempts?|Login History|Setup Audit Trail|Field History|Apex Jobs|Login History records authentication attempts and related details.
Auditing and Monitoring|Which tool recommends improvements based on org configuration?|Salesforce Optimizer|Schema Builder|Data Loader|Health Check only|Optimizer analyzes features and configuration and suggests improvements.
Auditing and Monitoring|What compares security settings against a baseline standard?|Health Check|Event Monitoring|Field History|Debug Log|Health Check scores settings against Salesforce or custom baselines.
Cloud Applications|Opportunity splits must total what percentage for revenue splits?|100%|Any amount|50%|They cannot be edited|Revenue splits must total 100 percent.
Cloud Applications|Which feature assigns Accounts and Opportunities by geography or rules?|Enterprise Territory Management|Role hierarchy|Account teams only|Lead assignment|Territory Management models flexible market-based access and assignment.
Cloud Applications|Support needs milestone timers and service terms. Configure?|Entitlements and milestones|Escalation rules only|Queues only|Knowledge categories|Entitlements and milestones track support eligibility and time commitments.
Cloud Applications|Knowledge visibility must vary by audience and subject. Use?|Data categories and channel visibility|Record types only|Queues|Forecast categories|Categories classify articles while channels govern audience visibility.
Cloud Applications|Which feature guides sellers through stage-specific fields and coaching?|Path|Forecasting|Kanban only|Territories|Path presents key fields and guidance for each process stage.
Cloud Applications|Cases must route based on criteria when created. Use?|Case assignment rules|Escalation rules|Auto-response only|Approval process|Assignment rules route new cases to users or queues.
Cloud Applications|A service deadline is missed and management must be notified. Use?|Milestone action|Lead assignment|Opportunity split|Forecast adjustment|Milestone actions respond to warning or violation timing.
Data and Analytics|Identify existing duplicate Accounts at scale. Use?|Duplicate Jobs with matching rules|Mass Transfer|Schema Builder|Weekly export|Duplicate Jobs scan existing records using matching rules.
Data and Analytics|Executives need dashboards filtered for the logged-in viewer. Use?|Dynamic dashboard|Reporting snapshot|Joined report|Bucket field|Dynamic dashboards run as the viewing user.
Data and Analytics|Store report totals monthly for historical comparison. Use?|Reporting snapshot|Dashboard filter|Cross filter|Row-level formula|Reporting snapshots save summarized report results on a schedule.
Data and Analytics|Show Accounts without Opportunities in a report. Use?|Cross filter|Bucket field|Summary formula|Dashboard filter|Cross filters include or exclude records based on related objects.
Data and Analytics|Combine blocks from different report types in one report. Use?|Joined report|Matrix report|Tabular report|Reporting snapshot|Joined reports display multiple report blocks with shared groupings.
Data and Analytics|Categorize numeric ranges without creating a field. Use?|Bucket field|Summary formula|Custom metadata|Cross filter|Bucket fields categorize report values without changing the object.
Data and Analytics|Which feature validates import records against duplicate policy?|Duplicate rules|Sharing rules|Restriction rules|Escalation rules|Duplicate rules determine whether matching records are allowed or blocked.
Data and Analytics|Mass update millions of records with API support. Best tool?|Data Loader|Import Wizard|List view inline edit|Schema Builder|Data Loader supports large volumes and automated command-line operations.
Environment and Deployment|A validation rule references a new field. What must the change set include?|Both components and dependencies|Rule only|Field only|Object data|Dependent metadata must be deployed together.
Environment and Deployment|Which sandbox includes a full copy of production data?|Full sandbox|Developer sandbox|Developer Pro|Scratch org|A Full sandbox replicates production metadata and data.
Environment and Deployment|What should be run before a production change-set deployment?|Validate inbound change set|Refresh production|Delete tests|Data export only|Validation checks dependencies and tests without committing changes.
Environment and Deployment|Which sandbox is best for development with limited data storage?|Developer sandbox|Full sandbox|Partial Copy only|Production clone|Developer sandboxes are intended for coding and configuration work.
Process Automation|Need guided user input and branching from a record page. Use?|Screen Flow|Before-save flow|Scheduled flow|Approval only|Screen Flows provide interactive screens and branching.
Process Automation|Fast update to fields on the triggering record. Use?|Before-save record-triggered flow|After-save flow|Screen flow|Approval process|Before-save flows avoid an extra database update.
Process Automation|Update related records after a record commits. Use?|After-save record-triggered flow|Before-save flow|Autolaunched flow only|Formula field|After-save flows can create and update related records.
Process Automation|Prevent repeat execution when a field has not meaningfully changed. Use?|Entry conditions with prior-value checks|Scheduled path|Screen component|Queue|Prior-value checks restrict automation to meaningful transitions.
Process Automation|Route a record through formal multi-step sign-off. Use?|Approval process|Before-save flow|Formula field|Assignment rule|Approval processes provide submission, approvers, lock, and actions.
Process Automation|Run automation every night independent of a record change. Use?|Schedule-triggered flow|Before-save flow|Screen flow|Approval process|Schedule-triggered flows run at a defined time and frequency.
Process Automation|Wait five days after a date before sending a reminder. Use?|Scheduled path|Before-save update|Immediate action only|Validation rule|Scheduled paths defer flow actions relative to a time source.
Process Automation|Reusable no-screen logic invoked by another flow. Use?|Autolaunched flow|Screen flow|Approval process|Workflow email alert|Autolaunched flows encapsulate reusable logic without UI.
Process Automation|Which tool evaluates a value dynamically without storing it?|Formula field|Roll-up summary only|Scheduled flow|Approval process|Formula fields calculate values when records are queried.
Process Automation|A flow faults while creating a record. Best design?|Connect fault path and log actionable details|Ignore the fault|Add a loop|Use a page layout|Fault paths provide controlled error handling and diagnostics.
Process Automation|Apply different automation only when Status changes to Closed. Use?|Is Changed plus prior/current criteria|Run every update|Scheduled flow|Manual share|Change detection ensures transition-specific execution.
Process Automation|Complex logic exceeds declarative limits and needs transaction control. Consider?|Invocable Apex with Flow|More page layouts|A dashboard|A sharing rule|Invocable Apex can extend Flow for code-appropriate requirements.
`.trim();

const baseQuestions:Question[]=raw.split("\n").map(line=>{const [domain,prompt,correct,...rest]=line.split("|");const rationale=rest.pop()!;const options=[correct,...rest];return{domain,prompt,options,answer:0,answers:[0],select:1,rationale}});
const extraRaw=`
Security and Access|A company needs different authentication assurance for ordinary reports and a sensitive application. What should the administrator configure?|Session security levels and high-assurance requirements|A second role hierarchy|A public group|A dashboard filter|Session security levels can require stronger authentication only for sensitive resources.
Security and Access|External auditors need read-only access to a narrow set of records for one month. What is the least-privilege design?|Time-bounded permission sets plus targeted sharing|System Administrator profiles|View All Data|Move auditors above executives in the hierarchy|Temporary permissions and narrow sharing avoid broad permanent access.
Security and Access|A manager can see a record but cannot run the report containing it. What should be checked first?|Report folder access|Organization-wide defaults|Field history tracking|Login hours|Report visibility also requires access to the folder containing the report.
Security and Access|A user gains access through several permission sets and the source is unclear. Which tool helps explain effective access?|User Access Summary|Schema Builder|Optimizer only|Data Export|User Access Summary consolidates permissions assigned through profiles and permission sets.
Security and Access|Sales users need access to Accounts in their assigned markets even when ownership changes. Best scalable model?|Enterprise Territory Management|Manual sharing|A single queue|Login IP ranges|Territories provide market-based access independent of ownership hierarchy.
Security and Access|A permission set group grants too much access from one component set. How should the admin remove only selected permissions?|Use a muting permission set|Clone every profile|Add a restriction rule|Change OWD|Muting permission sets suppress selected permissions within a permission set group.
Security and Access|A custom object must inherit access from its parent record. Which relationship supports this security behavior?|Master-detail relationship|Lookup relationship|External lookup|Hierarchical relationship|A detail record inherits ownership and sharing from its master.
Security and Access|Login attempts from known corporate networks should avoid extra identity verification without blocking other locations. Use?|Trusted IP ranges|Profile login IP ranges|Restriction rules|Sharing rules|Trusted ranges reduce verification challenges; profile ranges would block outside access.
Security and Access|A user should manage password resets but not modify security configuration. Best approach?|Delegated administration|Modify All Data|System Administrator profile|Role hierarchy|Delegated administration grants defined user-management duties without full Setup control.
Security and Access|Sensitive opportunities should remain hidden even from users who receive broader sharing access. Which feature can further filter visibility?|Restriction rules|Sharing rules|Account teams|Role hierarchy|Restriction rules can narrow the records visible after baseline sharing grants access.
Objects and Applications|A component should appear only when Opportunity Amount exceeds a threshold. What should be configured?|Dynamic component visibility in Lightning App Builder|A compact layout|A search layout|A global value set|Lightning component visibility can evaluate record field criteria.
Objects and Applications|Two departments share an object but need different status values and page experiences. Use?|Record types with business processes and page layouts|Two role hierarchies|Two OWD models|Dashboard filters|Record types separate processes, values, and page assignments on one object.
Objects and Applications|Users must relate a child to a parent but still own and share the child independently. Relationship?|Lookup|Master-detail|Junction master only|Hierarchical|Lookup preserves separate ownership and sharing.
Objects and Applications|A lookup parent may be deleted, but child records should remain. Configure?|Clear the lookup value on delete|Restricted delete|Cascade delete|Roll-up summary|Lookup delete behavior can clear the reference while retaining children.
Objects and Applications|A formula references data from a related parent. What type of formula is appropriate?|Cross-object formula|Summary formula|Bucket formula|Validation-only formula|Cross-object formulas traverse relationships to display parent data.
Objects and Applications|An admin wants to analyze Lightning record-page performance before activation. Use?|Analyze button in Lightning App Builder|Schema Builder|Optimizer report only|Debug log|The Analyze feature flags page-performance issues and recommendations.
Objects and Applications|A custom app needs distinct navigation, branding, and utility items. Configure?|Lightning App Manager|Object Manager|Sharing Settings|Approval Process|App Manager controls Lightning app branding, navigation, and options.
Objects and Applications|A dependent picklist should offer values based on another field. Configure?|Controlling and dependent fields|Global value set only|Record ownership|Compact layout|Field dependencies filter available dependent picklist values.
Objects and Applications|A child needs to move between parents in a master-detail model. What must be enabled?|Allow reparenting|Grant Access Using Hierarchies|Cascade delete|External ID|Allow reparenting permits changing the master reference.
Objects and Applications|A custom console needs persistent productivity tools. What should be added?|Utility bar items|Compact layouts|Search layouts|Forecast categories|The utility bar provides persistent tools within a Lightning app.
Auditing and Monitoring|Legal requires retained history for selected fields beyond standard history limits. Use?|Field Audit Trail retention policy|Setup Audit Trail|Login History|Recycle Bin|Field Audit Trail supports long-term policy-based field history retention.
Auditing and Monitoring|An admin needs to determine who changed a permission setting yesterday. Check?|Setup Audit Trail|Event log file for page views|Field History|Case History|Setup Audit Trail records administrative configuration changes.
Auditing and Monitoring|Security wants to detect unusually large report exports. Use?|Event Monitoring report-export events|Debug logs|Login hours|Schema Builder|Event Monitoring exposes detailed user activity such as report exports.
Auditing and Monitoring|A flow fails only for one user. What combination best supports diagnosis?|Flow error details and a debug log run as that user|Data Export and Recycle Bin|Health Check and OWD|A compact layout and Path|User-context debugging reveals permissions and runtime path failures.
Auditing and Monitoring|An upcoming release may change access behavior. Where should the admin review and test it?|Release Updates|Setup Audit Trail only|Login History|Data Loader|Release Updates lists pending changes and activation deadlines.
Auditing and Monitoring|Security settings must be measured against the company’s own standard. Use?|Custom baseline in Health Check|A dashboard filter|A report snapshot|A matching rule|Health Check supports Salesforce and imported custom baselines.
Auditing and Monitoring|An integration user is making unexpected API calls. Which event data is most relevant?|API event logs|Field history|Setup Audit Trail only|Opportunity history|API event logs identify API activity, users, clients, and timing.
Auditing and Monitoring|A production issue must be reproduced without exposing sensitive customer data. Best practice?|Use a sandbox with masked or limited data|Copy all production data to Developer sandbox manually|Debug directly in production only|Email exports to developers|Limit and mask nonproduction data to support troubleshooting and compliance.
Auditing and Monitoring|An admin wants a high-level assessment of unused features and configuration improvements. Use?|Salesforce Optimizer|Login History|Field Audit Trail|Territory reports|Optimizer analyzes configuration and recommends improvements.
Auditing and Monitoring|Which record shows whether a scheduled Flow interview failed?|Paused and Failed Flow Interviews|Setup Audit Trail only|Recycle Bin|Login History|Flow interview monitoring exposes paused and failed automation instances.
Cloud Applications|A company sells products at different prices to two markets. Configure?|Multiple price books with price book entries|Two role hierarchies|Opportunity splits|Forecast adjustments|Price books support distinct product pricing for different sales contexts.
Cloud Applications|Revenue should be recognized in monthly quantities on an Opportunity Product. Use?|Product schedules|Opportunity teams|Account teams|Case milestones|Product schedules distribute revenue or quantity across dates.
Cloud Applications|Management needs forecast totals grouped by sales territory. Which capabilities work together?|Collaborative Forecasts and Enterprise Territory Management|Knowledge and Entitlements|Queues and Omni-Channel|Path and Kanban only|Forecasting can use territory-based forecast hierarchies.
Cloud Applications|Agents need work routed based on capacity and skills across service channels. Use?|Omni-Channel routing|Case escalation only|Account teams|Opportunity splits|Omni-Channel routes work according to capacity, status, and routing configuration.
Cloud Applications|Customers should see only Knowledge articles appropriate for their product line. Use?|Data category visibility|Record ownership only|Forecast categories|Opportunity teams|Data category visibility filters Knowledge content by audience and classification.
Cloud Applications|A support contract provides different response deadlines by severity. Configure?|Entitlement process with milestones|Case assignment only|Lead escalation|Sales process|Entitlement milestones track time-dependent support commitments.
Cloud Applications|Sales operations needs to adjust a forecast without changing opportunity amounts. Use?|Forecast adjustment|Opportunity split|Product schedule|Territory exclusion|Authorized forecast users can apply forecast adjustments separately from records.
Cloud Applications|A quote must synchronize line items with its Opportunity. What should the admin enable?|Quote syncing|Revenue schedules|Forecast quotas|Order reduction|Quote syncing connects a selected quote and its products to the Opportunity.
Cloud Applications|Agents need a workspace showing multiple records and utility tools. Use?|Service Console app|A standard navigation app only|Schema Builder|A dashboard folder|Console apps provide tabbed workspaces and service productivity tools.
Cloud Applications|A case should automatically escalate when unresolved for a defined period. Use?|Escalation rule|Assignment rule only|Auto-response rule|Opportunity workflow|Escalation rules reassign or notify based on case age and criteria.
Data and Analytics|A custom report must show Accounts whether or not they have related custom records. Configure?|Custom report type relationship with or without child records|Cross filter only|Joined report only|Bucket field|Custom report type relationships define whether parent records without children appear.
Data and Analytics|A report needs the percentage each row contributes to a group total. Use?|Custom summary formula|Row-level formula only|Bucket field|Dashboard filter|Summary formulas calculate values at grouping and grand-total levels.
Data and Analytics|A nightly integration must upsert records reliably. Which field supports matching?|External ID field|Auto-number only|Formula field|Encrypted field|External IDs allow upsert operations to match external records.
Data and Analytics|Archived transaction data must remain queryable at massive scale on-platform. Consider?|Big Objects|Recycle Bin|Reporting Snapshot|Field History|Big Objects store and query very large historical datasets with defined indexes.
Data and Analytics|Users need live access to external records without copying them into Salesforce. Use?|Salesforce Connect external objects|Weekly Data Loader import|Reporting snapshot|Duplicate job|External objects virtualize data held outside Salesforce.
Data and Analytics|A dashboard viewer needs to choose region at runtime. Configure?|Dashboard filter|Dynamic dashboard only|Bucket field|Row-level formula|Dashboard filters let viewers select values applied to components.
Data and Analytics|Two datasets share a grouping but require different report types. Use?|Joined report|Matrix report only|Tabular report|Reporting snapshot|Joined reports combine blocks from different report types.
Data and Analytics|Prevent duplicate Contacts during both manual entry and import. Use?|Matching rule plus duplicate rule|Validation rule only|Sharing rule|Cross filter|Matching identifies potential duplicates and duplicate rules control the save behavior.
Data and Analytics|A one-time import of 30,000 Accounts is needed by a nontechnical admin. Best standard tool?|Data Import Wizard|Schema Builder|Mass Transfer|Reporting snapshot|The wizard supports guided imports within its supported object and volume limits.
Data and Analytics|A report must calculate a value separately for every record. Use?|Row-level formula|Custom summary formula|Dashboard filter|Reporting snapshot|Row-level formulas calculate once per report row.
Environment and Deployment|A team needs a sandbox containing a representative subset of production records. Use?|Partial Copy sandbox with a template|Developer sandbox|Scratch org only|Full sandbox without data|Partial Copy uses a sandbox template to select data.
Environment and Deployment|A change set upload omits a referenced component. What should happen before deployment?|Add dependencies and validate inbound change set|Deploy and repair production later|Export all production data|Refresh the source sandbox|Validation surfaces missing dependencies before changes are committed.
Environment and Deployment|A managed package component must be modified by the customer. Is that generally supported?|No, managed components are protected according to package rules|Yes, all package metadata is editable|Only through Data Loader|Only by changing OWD|Managed packaging protects distributed intellectual property and upgrade paths.
Environment and Deployment|User acceptance testing needs production-like data and maximum storage. Use?|Full sandbox|Developer sandbox|Developer Pro only|Trailhead Playground|Full sandboxes provide a complete copy for staging and performance testing.
Environment and Deployment|Metadata must move between related orgs using a declarative deployment tool. Use?|Change sets|Data Import Wizard|Weekly Export|Territory assignment|Change sets move supported metadata between connected orgs.
Environment and Deployment|Why should destructive changes be separated and carefully sequenced?|Dependencies may still reference components being removed|They always delete production data|They bypass all tests|They cannot be deployed|Removing metadata before dependents are updated can break deployment or behavior.
Environment and Deployment|A sandbox contains valuable configuration changes before refresh. What should happen first?|Move or retrieve the changes before refresh|Refresh immediately|Export only record data|Delete the sandbox|Refreshing replaces sandbox metadata and data from its source.
Environment and Deployment|Which practice reduces production deployment risk for a large release?|Validate, test, document dependencies, and plan rollback|Disable all validation rules permanently|Deploy at peak hours|Skip user acceptance testing|Structured validation and rollback planning reduce change risk.
Environment and Deployment|A package should expose editable components and source to installers. Choose?|Unmanaged package|Managed package|Full sandbox|Change set only|Unmanaged packages distribute editable components without managed upgrade protection.
Environment and Deployment|What can a sandbox template control?|Objects and records copied to Partial or Full sandboxes|Profile login hours|Change-set dependencies|Managed package namespaces|Templates select related production data for supported sandbox copies.
Process Automation|A record-triggered flow should run only when a record first meets criteria. Configure?|Updated records: only when updated to meet condition requirements|Every update regardless of criteria|A screen component|A dashboard filter|The entry option prevents repeat runs while criteria remain true.
Process Automation|A before-save flow and validation rule both affect a field. Why does order matter?|Before-save updates occur before validation rules evaluate|Validation always runs first|Flows never run during save|Only Apex has an order of execution|Before-save flow values can cause subsequent validation to pass or fail.
Process Automation|Several flows duplicate the same calculation. Best maintainable design?|Move logic to a reusable autolaunched subflow|Copy it into more flows|Use page layouts|Create sharing rules|Subflows centralize reusable declarative logic.
Process Automation|A flow must process a collection efficiently. Best design principle?|Use collection operations and minimize data elements inside loops|Put Get Records and Update Records inside every loop|Create one scheduled path per item|Use screen components|Bulk-safe flow design avoids database operations inside loops.
Process Automation|An approval should route to the submitter’s manager. What user data is essential?|An active manager on the user record|A territory assignment|A dashboard folder|A compact layout|Manager-based approval routing depends on the user’s Manager field.
Process Automation|A record update invokes Flow and Apex automation. What must the admin evaluate?|Complete order of execution and possible recursion|Only page layout assignment|Dashboard running user|Knowledge channels|Mixed automation can re-enter save order and cause repeated updates.
Process Automation|A flow needs to perform work only if a related record exists. Use?|Get Records followed by a Decision|A screen on every run|A sharing rule|An escalation rule|A Decision can branch based on whether the query returned a record.
Process Automation|A scheduled path is not firing. What should the admin verify first?|Time source, entry criteria, default workflow user, and scheduled jobs|Page layout fields only|Report folder access|Role hierarchy|Scheduled paths depend on valid scheduling inputs and runtime configuration.
Process Automation|A business process needs an admin-defined table of thresholds reusable in Flow. Use?|Custom metadata records referenced by Flow|Hard-code every value in Decisions|A dashboard table|Manual sharing|Custom metadata externalizes configuration and can be deployed.
Process Automation|Users need a clear error when a record violates complex cross-field logic. Use?|Validation rule with a precise error message|Sharing rule|Auto-response rule|Dashboard filter|Validation rules block invalid saves and explain required corrections.
`.trim();
const extras:Question[]=extraRaw.split("\n").map(line=>{const [domain,prompt,correct,w1,w2,w3,rationale]=line.split("|");return{domain,prompt,options:[correct,w1,w2,w3],answer:0,answers:[0],select:1,rationale}});
const variants:Question[]=extras.map((q,i)=>({...q,prompt:`${q.prompt} ${i%2===0?"Choose the most secure and scalable answer.":"Choose the best-practice answer."}`}));
const secondVariants:Question[]=extras.map((q,i)=>({...q,prompt:`A second organization faces this requirement: ${q.prompt.replace(/^A company |^An administrator |^A team |^A user /,"The team ")} ${i%2===0?"What should its administrator recommend?":"What should be evaluated first?"}`}));
const multiRaw=`
Security and Access|A company enables Person Accounts. Which two statements are true?|A Person Account combines Account and Contact behavior|Person Accounts use specific record types|Person Accounts can be disabled freely after activation|Every business Account automatically becomes a Person Account|Person Accounts represent individuals and depend on Person Account record types; enabling them is a significant, effectively permanent org decision.
Security and Access|Users need Contacts related to more than one Account. Which two capabilities apply?|Contacts to Multiple Accounts preserves one direct Account relationship|Additional Account relationships use Account Contact Relationship records|Every relationship changes Contact ownership|It requires converting Contacts to Person Accounts|The standard feature preserves the primary Account while modeling indirect relationships through Account Contact Relationships.
Security and Access|Which two controls govern field access rather than record access?|Field-level security|Permission-set field permissions|Organization-wide defaults|Role hierarchy|Field permissions determine visibility and editability; OWD and roles govern record-level access.
Objects and Applications|Which two behaviors are native to master-detail relationships?|Detail records inherit owner and sharing from the master|Roll-up summary fields can summarize detail records|The detail always has an independent owner|Parent deletion never affects details|Master-detail supplies inherited security and native roll-ups, and parent deletion cascades.
Objects and Applications|Which two features can tailor a Lightning record page without creating a separate object?|Dynamic Forms|Component visibility filters|Organization-wide defaults|Matching rules|Dynamic Forms and visibility rules tailor fields and components on Lightning pages.
Objects and Applications|Which two items can a Lightning app configure?|Navigation items|Utility bar|Organization-wide defaults|Duplicate matching logic|Lightning App Manager controls app navigation and utility tools, not org security or duplicate logic.
Auditing and Monitoring|An admin investigates an access change after a release. Which two areas should be reviewed first?|Setup Audit Trail|Release Updates|Recycle Bin|Opportunity History|Setup Audit Trail shows admin changes, while Release Updates shows pending platform changes affecting behavior.
Auditing and Monitoring|Which two activities can Event Monitoring help analyze?|Report exports|API usage|Page-layout assignments|Master-detail cascade deletes|Event log files include report-export and API activity, among many user events.
Auditing and Monitoring|Which two practices protect sensitive data in nonproduction environments?|Limit copied data with appropriate sandbox strategy|Mask sensitive values before broad developer access|Give every developer production access|Email production exports to personal accounts|Data minimization and masking reduce compliance exposure in sandboxes.
Cloud Applications|Which two features are central to managing service-level commitments?|Entitlements|Milestones|Opportunity splits|Lead conversion|Entitlements define support eligibility and milestones track required service steps and time targets.
Cloud Applications|Which two capabilities help route and manage agent work?|Omni-Channel|Service Console|Collaborative Forecasts|Opportunity Product schedules|Omni-Channel routes work and the Service Console provides the multi-record agent workspace.
Cloud Applications|Which two records are directly involved when selling catalog products on Opportunities?|Price Book Entry|Opportunity Product|Knowledge Article|Case Milestone|Price Book Entries define selectable product prices, and Opportunity Products are the quoted line items.
Data and Analytics|Which two reporting tools compare or combine complex datasets without changing object data?|Joined reports|Cross filters|Validation rules|Sharing rules|Joined reports combine blocks and cross filters include or exclude records based on related data.
Data and Analytics|Which two features support reliable external-system data loads?|External ID fields|Upsert operations|Dashboard filters|Compact layouts|External IDs provide matching keys and upsert inserts or updates based on those keys.
Data and Analytics|Which two tools help manage duplicates?|Matching rules|Duplicate rules|Escalation rules|Territory rules|Matching rules define similarity and duplicate rules control the user or API save behavior.
Environment and Deployment|Which two actions reduce change-set deployment risk?|Validate the inbound change set|Include and review dependencies|Refresh production before every deployment|Remove tests from the target org|Validation and dependency review catch failures before committing metadata.
Environment and Deployment|Which two sandbox types can provide production data for testing?|Partial Copy|Full|Developer|Scratch org by default|Partial Copy and Full sandboxes copy production records; Developer sandboxes contain metadata only by default.
Environment and Deployment|Which two statements about managed packages are true?|They support versioned upgrades|Some components are protected from subscriber modification|Subscribers can edit every component|They are the same as change sets|Managed packages provide protected distribution and an upgrade path.
Process Automation|Which two practices make record-triggered flows bulk-safe?|Keep Get and Update elements outside loops where possible|Use collections for batched operations|Query the database once per loop item|Create a separate flow interview manually for every record|Collection-based operations and avoiding database work in loops support bulk processing.
Process Automation|Which two tools help troubleshoot a failing Flow?|Flow debug details|Fault paths with logging or notifications|Dashboard filters|Sharing rules only|Debug details expose the execution path and fault connectors provide controlled diagnostics.
Process Automation|Which two statements about save order are correct?|Before-save record-triggered flows run before validation rules|After-save automation can update related records|Validation rules always run before before-save flows|Screen flows automatically run on every record save|Before-save values are available to validation, while after-save automation can act on related records.
`.trim();
const multis:Question[]=multiRaw.split("\n").map(line=>{const [domain,prompt,c1,c2,w1,w2,rationale]=line.split("|");return{domain,prompt,options:[c1,c2,w1,w2],answer:0,answers:[0,1],select:2,rationale}});
export const questions:Question[]=[...baseQuestions,...variants,...secondVariants,...multis];
export const domains=[
 {name:"Security and Access",weight:20,color:"#f4a55e"},{name:"Objects and Applications",weight:19,color:"#72b9df"},{name:"Auditing and Monitoring",weight:10,color:"#9d8ce0"},{name:"Cloud Applications",weight:11,color:"#e7859f"},{name:"Data and Analytics",weight:13,color:"#63be9b"},{name:"Environment and Deployment",weight:7,color:"#d9a35f"},{name:"Process Automation",weight:20,color:"#ed725f"}
];
